limit_req_zone $binary_remote_addr zone=lk_tournament_participants_by_ip:10m rate=60r/m;
limit_req_zone $binary_remote_addr zone=lk_tournament_participants_refresh_by_ip:10m rate=10r/m;

log_format lk_tournament_participants_json escape=json
    '{'
    '"ts":"$time_iso8601",'
    '"host":"$host",'
    '"remote_addr":"$remote_addr",'
    '"xff":"$http_x_forwarded_for",'
    '"method":"$request_method",'
    '"uri":"$request_uri",'
    '"exerciseId":"$arg_exerciseId",'
    '"status":$status,'
    '"request_time":$request_time,'
    '"upstream_response_time":"$upstream_response_time",'
    '"cache":"$sent_http_x_lk_participants_cache"'
    '}';
