const ctx = msg._subscriptionPricePreview;
if (!ctx) return null;
msg.statusCode = ctx.statusCode || 200;
msg.headers = { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'Access-Control-Allow-Origin': '*', 'X-Correlation-ID': msg._msgid, 'Access-Control-Expose-Headers': 'X-Correlation-ID' };
msg.payload = ctx.done && ctx.error ? { error: { code: ctx.error } } : { quotes: ctx.quotes || [] };
delete msg._subscriptionPricePreview;
delete msg.url; delete msg.method; delete msg.error;
delete msg._managedSubscriptionPolicyInput; delete msg._managedSubscriptionPolicyDecision;
delete msg._subscriptionPricePreviewInput;
delete msg._subscriptionPricePreviewDecision;
return msg;
