import fs from 'node:fs';
import path from 'node:path';

const srcPath = '/Users/zver/Desktop/project-fixed 6/ЛК03_03_26.with_games.json';
const outPath = '/Users/zver/Desktop/project-fixed 6/ЛК03_03_26.with_games_chat.json';
const fnDir = '/Users/zver/Desktop/project-fixed 6/scripts/nodered_chat_nodes';

const readFn = (name) => fs.readFileSync(path.join(fnDir, name), 'utf8');

const fnChatPostPrepare = readFn('fn_chat_post_prepare.js');
const fnChatPostBuildInsert = readFn('fn_chat_post_build_insert.js');
const fnChatPostResponse = readFn('fn_chat_post_response.js');
const fnChatGetPrepare = readFn('fn_chat_get_prepare.js');
const fnChatGetBuildQuery = readFn('fn_chat_get_build_query.js');
const fnChatGetResponse = readFn('fn_chat_get_response.js');
const fnChatReadPrepare = readFn('fn_chat_read_prepare.js');
const fnChatReadInsert = readFn('fn_chat_read_insert.js');
const fnChatReadResponse = readFn('fn_chat_read_response.js');
const fnChatListPrepare = readFn('fn_chat_list_prepare.js');
const fnChatListResponse = readFn('fn_chat_list_response.js');

const raw = fs.readFileSync(srcPath, 'utf8');
const flow = JSON.parse(raw);

const NEW_IDS = new Set([
  'chat_comment_001',
  'chat_db_client_001',
  'chat_post_in_001',
  'chat_post_fn_prepare_001',
  'chat_post_find_game_001',
  'chat_post_fn_insert_001',
  'chat_post_insert_msg_001',
  'chat_post_fn_response_001',
  'chat_post_http_resp_001',
  'chat_post_debug_001',

  'chat_get_in_001',
  'chat_get_fn_prepare_001',
  'chat_get_find_game_001',
  'chat_get_fn_query_001',
  'chat_get_find_messages_001',
  'chat_get_fn_response_001',
  'chat_get_http_resp_001',
  'chat_get_debug_001',

  'chat_read_in_001',
  'chat_read_fn_prepare_001',
  'chat_read_find_game_001',
  'chat_read_fn_insert_001',
  'chat_read_insert_001',
  'chat_read_fn_response_001',
  'chat_read_http_resp_001',
  'chat_read_debug_001',

  'chat_list_in_001',
  'chat_list_fn_prepare_001',
  'chat_list_find_001',
  'chat_list_fn_response_001',
  'chat_list_http_resp_001',
  'chat_list_debug_001',
]);

const filtered = flow.filter((node) => !NEW_IDS.has(node.id));
const tabId = '1e95dcebc274ac6c';

const chatNodes = [
  {
    id: 'chat_comment_001',
    type: 'comment',
    z: tabId,
    name: 'LK games chat (separate DB games_chat)',
    info: 'Хранение сообщений чата игры в отдельной БД games_chat. Авторизация по участию в игре.',
    x: 280,
    y: 3260,
    wires: [],
  },
  {
    id: 'chat_db_client_001',
    type: 'mongodb4-client',
    name: 'lk_games_chat_db',
    protocol: 'mongodb',
    hostname: '147.45.254.160',
    port: '27017',
    dbName: 'games_chat',
    appName: '',
    authSource: 'admin',
    authMechanism: 'DEFAULT',
    tls: false,
    tlsCAFile: '',
    tlsCertificateKeyFile: '',
    tlsInsecure: false,
    connectTimeoutMS: '30000',
    socketTimeoutMS: '0',
    minPoolSize: '0',
    maxPoolSize: '100',
    maxIdleTimeMS: '0',
    uri: 'mongodb://gen_user:l^RRk2kNPNqoC~@147.45.254.160:27017/games_chat?authSource=admin&directConnection=true&retryWrites=false',
    advanced: '{}',
    uriTabActive: 'tab-uri-advanced',
  },

  {
    id: 'chat_post_in_001',
    type: 'http in',
    z: tabId,
    name: 'LK game chat send',
    url: '/lk/games/:gameId/chat/messages',
    method: 'post',
    upload: false,
    swaggerDoc: '',
    x: 130,
    y: 3300,
    wires: [['chat_post_fn_prepare_001']],
  },
  {
    id: 'chat_post_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Chat send validate',
    func: fnChatPostPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 380,
    y: 3300,
    wires: [['chat_post_find_game_001'], ['chat_post_http_resp_001'], ['chat_post_debug_001']],
  },
  {
    id: 'chat_post_find_game_001',
    type: 'mongodb in',
    z: tabId,
    mongodb: 'mongo_lk',
    name: 'Find game for chat send',
    collection: 'lk_games',
    operation: 'find',
    x: 650,
    y: 3260,
    wires: [['chat_post_fn_insert_001']],
  },
  {
    id: 'chat_post_fn_insert_001',
    type: 'function',
    z: tabId,
    name: 'Build chat message doc',
    func: fnChatPostBuildInsert,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 930,
    y: 3260,
    wires: [['chat_post_insert_msg_001'], ['chat_post_http_resp_001'], ['chat_post_debug_001']],
  },
  {
    id: 'chat_post_insert_msg_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: 'chat_db_client_001',
    mode: 'collection',
    collection: 'chat_messages',
    operation: 'insertOne',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Insert chat message',
    x: 1190,
    y: 3260,
    wires: [['chat_post_fn_response_001']],
  },
  {
    id: 'chat_post_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Chat send response',
    func: fnChatPostResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1460,
    y: 3260,
    wires: [['chat_post_http_resp_001'], ['chat_post_debug_001']],
  },
  {
    id: 'chat_post_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1720,
    y: 3300,
    wires: [],
  },
  {
    id: 'chat_post_debug_001',
    type: 'debug',
    z: tabId,
    name: 'chat send debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1710,
    y: 3340,
    wires: [],
  },

  {
    id: 'chat_get_in_001',
    type: 'http in',
    z: tabId,
    name: 'LK game chat messages',
    url: '/lk/games/:gameId/chat/messages',
    method: 'get',
    upload: false,
    swaggerDoc: '',
    x: 140,
    y: 3400,
    wires: [['chat_get_fn_prepare_001']],
  },
  {
    id: 'chat_get_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Chat get validate',
    func: fnChatGetPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 380,
    y: 3400,
    wires: [['chat_get_find_game_001'], ['chat_get_http_resp_001'], ['chat_get_debug_001']],
  },
  {
    id: 'chat_get_find_game_001',
    type: 'mongodb in',
    z: tabId,
    mongodb: 'mongo_lk',
    name: 'Find game for chat read',
    collection: 'lk_games',
    operation: 'find',
    x: 650,
    y: 3360,
    wires: [['chat_get_fn_query_001']],
  },
  {
    id: 'chat_get_fn_query_001',
    type: 'function',
    z: tabId,
    name: 'Build chat messages query',
    func: fnChatGetBuildQuery,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 930,
    y: 3360,
    wires: [['chat_get_find_messages_001'], ['chat_get_http_resp_001'], ['chat_get_debug_001']],
  },
  {
    id: 'chat_get_find_messages_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: 'chat_db_client_001',
    mode: 'collection',
    collection: 'chat_messages',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find chat messages',
    x: 1200,
    y: 3360,
    wires: [['chat_get_fn_response_001']],
  },
  {
    id: 'chat_get_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Chat get response',
    func: fnChatGetResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1460,
    y: 3360,
    wires: [['chat_get_http_resp_001'], ['chat_get_debug_001']],
  },
  {
    id: 'chat_get_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1720,
    y: 3400,
    wires: [],
  },
  {
    id: 'chat_get_debug_001',
    type: 'debug',
    z: tabId,
    name: 'chat get debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1710,
    y: 3440,
    wires: [],
  },

  {
    id: 'chat_read_in_001',
    type: 'http in',
    z: tabId,
    name: 'LK game chat read',
    url: '/lk/games/:gameId/chat/read',
    method: 'post',
    upload: false,
    swaggerDoc: '',
    x: 130,
    y: 3500,
    wires: [['chat_read_fn_prepare_001']],
  },
  {
    id: 'chat_read_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Chat read validate',
    func: fnChatReadPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 380,
    y: 3500,
    wires: [['chat_read_find_game_001'], ['chat_read_http_resp_001'], ['chat_read_debug_001']],
  },
  {
    id: 'chat_read_find_game_001',
    type: 'mongodb in',
    z: tabId,
    mongodb: 'mongo_lk',
    name: 'Find game for read mark',
    collection: 'lk_games',
    operation: 'find',
    x: 650,
    y: 3460,
    wires: [['chat_read_fn_insert_001']],
  },
  {
    id: 'chat_read_fn_insert_001',
    type: 'function',
    z: tabId,
    name: 'Build read event doc',
    func: fnChatReadInsert,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 920,
    y: 3460,
    wires: [['chat_read_insert_001'], ['chat_read_http_resp_001'], ['chat_read_debug_001']],
  },
  {
    id: 'chat_read_insert_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: 'chat_db_client_001',
    mode: 'collection',
    collection: 'chat_reads',
    operation: 'insertOne',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Insert read event',
    x: 1180,
    y: 3460,
    wires: [['chat_read_fn_response_001']],
  },
  {
    id: 'chat_read_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Chat read response',
    func: fnChatReadResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1450,
    y: 3460,
    wires: [['chat_read_http_resp_001'], ['chat_read_debug_001']],
  },
  {
    id: 'chat_read_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1720,
    y: 3500,
    wires: [],
  },
  {
    id: 'chat_read_debug_001',
    type: 'debug',
    z: tabId,
    name: 'chat read debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1710,
    y: 3540,
    wires: [],
  },

  {
    id: 'chat_list_in_001',
    type: 'http in',
    z: tabId,
    name: 'LK chats by phone',
    url: '/lk/chats/by-phone',
    method: 'get',
    upload: false,
    swaggerDoc: '',
    x: 130,
    y: 3600,
    wires: [['chat_list_fn_prepare_001']],
  },
  {
    id: 'chat_list_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Build chats by phone query',
    func: fnChatListPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 390,
    y: 3600,
    wires: [['chat_list_find_001'], ['chat_list_http_resp_001'], ['chat_list_debug_001']],
  },
  {
    id: 'chat_list_find_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: 'chat_db_client_001',
    mode: 'collection',
    collection: 'chat_messages',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find chats by phone',
    x: 670,
    y: 3560,
    wires: [['chat_list_fn_response_001']],
  },
  {
    id: 'chat_list_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Build chats summary response',
    func: fnChatListResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 950,
    y: 3560,
    wires: [['chat_list_http_resp_001'], ['chat_list_debug_001']],
  },
  {
    id: 'chat_list_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1220,
    y: 3600,
    wires: [],
  },
  {
    id: 'chat_list_debug_001',
    type: 'debug',
    z: tabId,
    name: 'chat list debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1210,
    y: 3640,
    wires: [],
  },
];

filtered.push(...chatNodes);
fs.writeFileSync(outPath, JSON.stringify(filtered, null, 4), 'utf8');
console.log(`Patched flow written to: ${outPath}`);
console.log(`Total nodes: ${filtered.length}`);
