import fs from 'node:fs';
import path from 'node:path';

const workspaceRoot = process.cwd();
const outPath = path.resolve(workspaceRoot, 'lk_max_webhook_nodes_import.json');
const fnDir = path.resolve(workspaceRoot, 'scripts/nodered_max_nodes');
const tabId = 'f9f8d8f2a833ab13';

const readFn = (name) => fs.readFileSync(path.join(fnDir, name), 'utf8');
const fnMaxWebhookPrepare = readFn('fn_max_webhook_prepare.js');
const fnMaxClientLookupPrepare = readFn('fn_max_client_lookup_prepare.js');
const fnMaxSupportRoute = readFn('fn_max_support_route.js');

const flow = [
  {
    id: tabId,
    type: 'tab',
    label: 'MAX webhook',
    disabled: false,
    info: 'Прием входящих сообщений MAX и маршрутизация в мультиканальные support-диалоги',
  },
  {
    id: 'max_comment_001',
    type: 'comment',
    z: tabId,
    name: 'MAX inbound webhook',
    info: [
      'Вебхук принимает входящие сообщения MAX и нормализует их в msg.maxUpdate.',
      'Также доступен link-in для подключения существующего maxbot-receive без вебхука.',
      'После нормализации flow запрашивает состояние клиента через /lk/support/clients/resolve',
      'и отправляет событие в /lk/support/dialogs/events.',
      'Исходящие сервисные сообщения уходят в link-out "MAX outbound messages" — подключите его к существующему maxbot-send.',
    ].join('\n'),
    x: 280,
    y: 140,
    wires: [],
  },
  {
    id: 'max_webhook_in_001',
    type: 'http in',
    z: tabId,
    name: 'MAX webhook',
    url: '/integrations/max/webhook',
    method: 'post',
    upload: false,
    swaggerDoc: '',
    x: 120,
    y: 220,
    wires: [['max_webhook_fn_prepare_001']],
  },
  {
    id: 'max_link_in_001',
    type: 'link in',
    z: tabId,
    name: 'MAX raw receive',
    links: [],
    x: 115,
    y: 280,
    wires: [['max_webhook_fn_prepare_001']],
  },
  {
    id: 'max_webhook_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Normalize MAX inbound',
    func: fnMaxWebhookPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 390,
    y: 240,
    wires: [
      ['max_client_lookup_prepare_001'],
      ['max_webhook_http_resp_001'],
      ['max_webhook_debug_001'],
    ],
  },
  {
    id: 'max_client_lookup_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Prepare client lookup',
    func: fnMaxClientLookupPrepare,
    outputs: 1,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 680,
    y: 220,
    wires: [['max_client_lookup_http_001']],
  },
  {
    id: 'max_client_lookup_http_001',
    type: 'http request',
    z: tabId,
    name: 'Resolve support client',
    method: 'use',
    ret: 'obj',
    paytoqs: 'ignore',
    url: '',
    tls: '',
    persist: false,
    proxy: '',
    insecureHTTPParser: false,
    authType: '',
    senderr: false,
    headers: [],
    x: 930,
    y: 220,
    wires: [['max_support_route_001']],
  },
  {
    id: 'max_support_route_001',
    type: 'function',
    z: tabId,
    name: 'Route MAX support flow',
    func: fnMaxSupportRoute,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1200,
    y: 220,
    wires: [
      ['max_support_event_http_001'],
      ['max_outbound_link_out_001', 'max_outbound_debug_001'],
      ['max_webhook_debug_001'],
    ],
  },
  {
    id: 'max_support_event_http_001',
    type: 'http request',
    z: tabId,
    name: 'POST support event',
    method: 'use',
    ret: 'obj',
    paytoqs: 'ignore',
    url: '',
    tls: '',
    persist: false,
    proxy: '',
    insecureHTTPParser: false,
    authType: '',
    senderr: false,
    headers: [],
    x: 1470,
    y: 180,
    wires: [['max_support_event_debug_001']],
  },
  {
    id: 'max_outbound_link_out_001',
    type: 'link out',
    z: tabId,
    name: 'MAX outbound messages',
    mode: 'link',
    links: [],
    x: 1475,
    y: 240,
    wires: [],
  },
  {
    id: 'max_webhook_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 690,
    y: 280,
    wires: [],
  },
  {
    id: 'max_webhook_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX webhook debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 690,
    y: 340,
    wires: [],
  },
  {
    id: 'max_outbound_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX outbound debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 1470,
    y: 300,
    wires: [],
  },
  {
    id: 'max_support_event_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX support event debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 1740,
    y: 180,
    wires: [],
  },
];

fs.writeFileSync(outPath, `${JSON.stringify(flow, null, 2)}\n`);
console.log(`Wrote ${outPath}`);
