import fs from 'node:fs';
import path from 'node:path';
import { GAMES_MONGO4_CLIENT_ID, transformFlowToMongo4 } from './nodered_mongodb4_transform.mjs';

const workspaceRoot = process.cwd();
const nodeRedRoot = path.resolve(workspaceRoot, 'node-red');
const srcPath = path.resolve(nodeRedRoot, 'ЛК03_03_26.with_games_chat_results_communities.json');
const outPath = path.resolve(nodeRedRoot, 'ЛК03_03_26.with_games_chat_results_communities_support.json');
const importPath = path.resolve(nodeRedRoot, 'lk_support_dialog_nodes_import.json');
const fnDir = path.resolve(workspaceRoot, 'scripts/nodered_support_nodes');
const tabId = '1e95dcebc274ac6c';

const readFn = (name) => fs.readFileSync(path.join(fnDir, name), 'utf8');

const fnSupportEventPrepare = readFn('fn_support_event_prepare.js');
const fnSupportEventResolveClient = readFn('fn_support_event_resolve_client.js');
const fnSupportEventResolveDialog = readFn('fn_support_event_resolve_dialog.js');
const fnSupportEventResponse = readFn('fn_support_event_response.js');
const fnSupportClientResolvePrepare = readFn('fn_support_client_resolve_prepare.js');
const fnSupportClientResolveResponse = readFn('fn_support_client_resolve_response.js');
const fnSupportDialogListPrepare = readFn('fn_support_dialog_list_prepare.js');
const fnSupportDialogListResponse = readFn('fn_support_dialog_list_response.js');
const fnSupportDialogMessagesPrepare = readFn('fn_support_dialog_messages_prepare.js');
const fnSupportDialogMessagesResponse = readFn('fn_support_dialog_messages_response.js');
const fnSupportDialogReplyPrepare = readFn('fn_support_dialog_reply_prepare.js');
const fnSupportDialogReplyResolve = readFn('fn_support_dialog_reply_resolve.js');
const fnSupportDialogReplyResponse = readFn('fn_support_dialog_reply_response.js');
const fnSupportAnalyticsDailyPrepare = readFn('fn_support_analytics_daily_prepare.js');
const fnSupportAnalyticsDailyResponse = readFn('fn_support_analytics_daily_response.js');

const raw = fs.readFileSync(srcPath, 'utf8');
const sourceFlow = JSON.parse(raw);

const NEW_IDS = new Set([
  'support_comment_001',
  'support_client_resolve_in_001',
  'support_client_resolve_fn_prepare_001',
  'support_client_resolve_find_001',
  'support_client_resolve_fn_response_001',
  'support_client_resolve_http_resp_001',
  'support_client_resolve_debug_001',

  'support_event_in_001',
  'support_event_fn_prepare_001',
  'support_event_find_client_001',
  'support_event_fn_resolve_client_001',
  'support_event_update_client_001',
  'support_event_find_dialog_001',
  'support_event_fn_resolve_dialog_001',
  'support_event_update_dialog_001',
  'support_event_insert_message_001',
  'support_event_fn_response_001',
  'support_event_http_resp_001',
  'support_event_debug_001',

  'support_dialog_list_in_001',
  'support_dialog_list_fn_prepare_001',
  'support_dialog_list_find_001',
  'support_dialog_list_fn_response_001',
  'support_dialog_list_http_resp_001',
  'support_dialog_list_debug_001',

  'support_dialog_messages_in_001',
  'support_dialog_messages_fn_prepare_001',
  'support_dialog_messages_find_001',
  'support_dialog_messages_fn_response_001',
  'support_dialog_messages_http_resp_001',
  'support_dialog_messages_debug_001',

  'support_reply_in_001',
  'support_reply_fn_prepare_001',
  'support_reply_find_dialog_001',
  'support_reply_fn_resolve_001',
  'support_reply_update_dialog_001',
  'support_reply_insert_message_001',
  'support_reply_fn_response_001',
  'support_reply_http_resp_001',
  'support_reply_dispatch_debug_001',
  'support_reply_dispatch_link_out_001',
  'support_reply_debug_001',

  'support_analytics_in_001',
  'support_analytics_fn_prepare_001',
  'support_analytics_find_001',
  'support_analytics_fn_response_001',
  'support_analytics_http_resp_001',
  'support_analytics_debug_001',
]);

const filteredFlow = sourceFlow.filter((node) => !NEW_IDS.has(node.id));

const supportNodes = [
  {
    id: 'support_comment_001',
    type: 'comment',
    z: tabId,
    name: 'Support dialogs',
    info: [
      'Мультиканальные диалоги для MAX, Telegram, email, телефонии и Bitrix.',
      'Коллекции: support_clients, support_dialogs, support_messages.',
      'REST: resolve client, ingest event, list dialogs, dialog messages, admin reply, daily analytics.',
      'Сущность диалога завязана на клиенте и станции, а клиент поддерживает несколько телефонов и идентификаторов каналов.',
    ].join('\n'),
    x: 260,
    y: 5720,
    wires: [],
  },

  {
    id: 'support_client_resolve_in_001',
    type: 'http in',
    z: tabId,
    name: 'Support client resolve',
    url: '/lk/support/clients/resolve',
    method: 'get',
    upload: false,
    swaggerDoc: '',
    x: 130,
    y: 5780,
    wires: [['support_client_resolve_fn_prepare_001']],
  },
  {
    id: 'support_client_resolve_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Support client resolve prepare',
    func: fnSupportClientResolvePrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 400,
    y: 5780,
    wires: [
      ['support_client_resolve_find_001'],
      ['support_client_resolve_http_resp_001'],
      ['support_client_resolve_debug_001'],
    ],
  },
  {
    id: 'support_client_resolve_find_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_clients',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find support clients',
    x: 680,
    y: 5780,
    wires: [['support_client_resolve_fn_response_001']],
  },
  {
    id: 'support_client_resolve_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Support client resolve response',
    func: fnSupportClientResolveResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 970,
    y: 5780,
    wires: [
      ['support_client_resolve_http_resp_001'],
      ['support_client_resolve_debug_001'],
    ],
  },
  {
    id: 'support_client_resolve_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1250,
    y: 5780,
    wires: [],
  },
  {
    id: 'support_client_resolve_debug_001',
    type: 'debug',
    z: tabId,
    name: 'support client resolve debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1260,
    y: 5820,
    wires: [],
  },

  {
    id: 'support_event_in_001',
    type: 'http in',
    z: tabId,
    name: 'Support event ingest',
    url: '/lk/support/dialogs/events',
    method: 'post',
    upload: false,
    swaggerDoc: '',
    x: 120,
    y: 5880,
    wires: [['support_event_fn_prepare_001']],
  },
  {
    id: 'support_event_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Support event prepare',
    func: fnSupportEventPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 390,
    y: 5880,
    wires: [
      ['support_event_find_client_001'],
      ['support_event_http_resp_001'],
      ['support_event_debug_001'],
    ],
  },
  {
    id: 'support_event_find_client_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_clients',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find support client',
    x: 670,
    y: 5840,
    wires: [['support_event_fn_resolve_client_001']],
  },
  {
    id: 'support_event_fn_resolve_client_001',
    type: 'function',
    z: tabId,
    name: 'Resolve support client',
    func: fnSupportEventResolveClient,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 950,
    y: 5840,
    wires: [
      ['support_event_update_client_001'],
      ['support_event_find_dialog_001'],
      ['support_event_debug_001'],
    ],
  },
  {
    id: 'support_event_update_client_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_clients',
    operation: 'updateOne',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Upsert support client',
    x: 1240,
    y: 5780,
    wires: [],
  },
  {
    id: 'support_event_find_dialog_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_dialogs',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find support dialog',
    x: 1230,
    y: 5880,
    wires: [['support_event_fn_resolve_dialog_001']],
  },
  {
    id: 'support_event_fn_resolve_dialog_001',
    type: 'function',
    z: tabId,
    name: 'Resolve support dialog',
    func: fnSupportEventResolveDialog,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1510,
    y: 5880,
    wires: [
      ['support_event_update_dialog_001'],
      ['support_event_insert_message_001'],
      ['support_event_debug_001'],
    ],
  },
  {
    id: 'support_event_update_dialog_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_dialogs',
    operation: 'updateOne',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Upsert support dialog',
    x: 1790,
    y: 5840,
    wires: [],
  },
  {
    id: 'support_event_insert_message_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_messages',
    operation: 'insertOne',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Insert support message',
    x: 1790,
    y: 5920,
    wires: [['support_event_fn_response_001']],
  },
  {
    id: 'support_event_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Support event response',
    func: fnSupportEventResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 2050,
    y: 5920,
    wires: [
      ['support_event_http_resp_001'],
      ['support_event_debug_001'],
    ],
  },
  {
    id: 'support_event_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 2310,
    y: 5880,
    wires: [],
  },
  {
    id: 'support_event_debug_001',
    type: 'debug',
    z: tabId,
    name: 'support event debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 2310,
    y: 5920,
    wires: [],
  },

  {
    id: 'support_dialog_list_in_001',
    type: 'http in',
    z: tabId,
    name: 'Support dialogs list',
    url: '/lk/support/dialogs',
    method: 'get',
    upload: false,
    swaggerDoc: '',
    x: 120,
    y: 6000,
    wires: [['support_dialog_list_fn_prepare_001']],
  },
  {
    id: 'support_dialog_list_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Support dialogs list prepare',
    func: fnSupportDialogListPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 400,
    y: 6000,
    wires: [
      ['support_dialog_list_find_001'],
      ['support_dialog_list_http_resp_001'],
      ['support_dialog_list_debug_001'],
    ],
  },
  {
    id: 'support_dialog_list_find_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_dialogs',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find support dialogs',
    x: 690,
    y: 6000,
    wires: [['support_dialog_list_fn_response_001']],
  },
  {
    id: 'support_dialog_list_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Support dialogs list response',
    func: fnSupportDialogListResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 980,
    y: 6000,
    wires: [
      ['support_dialog_list_http_resp_001'],
      ['support_dialog_list_debug_001'],
    ],
  },
  {
    id: 'support_dialog_list_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1260,
    y: 6000,
    wires: [],
  },
  {
    id: 'support_dialog_list_debug_001',
    type: 'debug',
    z: tabId,
    name: 'support dialogs list debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1270,
    y: 6040,
    wires: [],
  },

  {
    id: 'support_dialog_messages_in_001',
    type: 'http in',
    z: tabId,
    name: 'Support dialog messages',
    url: '/lk/support/dialogs/:dialogId/messages',
    method: 'get',
    upload: false,
    swaggerDoc: '',
    x: 130,
    y: 6100,
    wires: [['support_dialog_messages_fn_prepare_001']],
  },
  {
    id: 'support_dialog_messages_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Support dialog messages prepare',
    func: fnSupportDialogMessagesPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 430,
    y: 6100,
    wires: [
      ['support_dialog_messages_find_001'],
      ['support_dialog_messages_http_resp_001'],
      ['support_dialog_messages_debug_001'],
    ],
  },
  {
    id: 'support_dialog_messages_find_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_messages',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find support dialog messages',
    x: 730,
    y: 6100,
    wires: [['support_dialog_messages_fn_response_001']],
  },
  {
    id: 'support_dialog_messages_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Support dialog messages response',
    func: fnSupportDialogMessagesResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1040,
    y: 6100,
    wires: [
      ['support_dialog_messages_http_resp_001'],
      ['support_dialog_messages_debug_001'],
    ],
  },
  {
    id: 'support_dialog_messages_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1340,
    y: 6100,
    wires: [],
  },
  {
    id: 'support_dialog_messages_debug_001',
    type: 'debug',
    z: tabId,
    name: 'support dialog messages debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1350,
    y: 6140,
    wires: [],
  },

  {
    id: 'support_reply_in_001',
    type: 'http in',
    z: tabId,
    name: 'Support dialog reply',
    url: '/lk/support/dialogs/:dialogId/reply',
    method: 'post',
    upload: false,
    swaggerDoc: '',
    x: 120,
    y: 6200,
    wires: [['support_reply_fn_prepare_001']],
  },
  {
    id: 'support_reply_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Support dialog reply prepare',
    func: fnSupportDialogReplyPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 420,
    y: 6200,
    wires: [
      ['support_reply_find_dialog_001'],
      ['support_reply_http_resp_001'],
      ['support_reply_debug_001'],
    ],
  },
  {
    id: 'support_reply_find_dialog_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_dialogs',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find reply dialog',
    x: 710,
    y: 6200,
    wires: [['support_reply_fn_resolve_001']],
  },
  {
    id: 'support_reply_fn_resolve_001',
    type: 'function',
    z: tabId,
    name: 'Resolve support reply',
    func: fnSupportDialogReplyResolve,
    outputs: 4,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1000,
    y: 6200,
    wires: [
      ['support_reply_update_dialog_001'],
      ['support_reply_insert_message_001'],
      ['support_reply_dispatch_link_out_001', 'support_reply_dispatch_debug_001'],
      ['support_reply_http_resp_001', 'support_reply_debug_001'],
    ],
  },
  {
    id: 'support_reply_update_dialog_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_dialogs',
    operation: 'updateOne',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Update reply dialog',
    x: 1290,
    y: 6160,
    wires: [],
  },
  {
    id: 'support_reply_insert_message_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_messages',
    operation: 'insertOne',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Insert reply message',
    x: 1290,
    y: 6240,
    wires: [['support_reply_fn_response_001']],
  },
  {
    id: 'support_reply_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Support reply response',
    func: fnSupportDialogReplyResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1550,
    y: 6240,
    wires: [
      ['support_reply_http_resp_001'],
      ['support_reply_debug_001'],
    ],
  },
  {
    id: 'support_reply_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1820,
    y: 6200,
    wires: [],
  },
  {
    id: 'support_reply_dispatch_link_out_001',
    type: 'link out',
    z: tabId,
    name: 'Support outbound dispatch',
    mode: 'link',
    links: [],
    x: 1295,
    y: 6320,
    wires: [],
  },
  {
    id: 'support_reply_dispatch_debug_001',
    type: 'debug',
    z: tabId,
    name: 'support reply dispatch debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1570,
    y: 6320,
    wires: [],
  },
  {
    id: 'support_reply_debug_001',
    type: 'debug',
    z: tabId,
    name: 'support reply debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1810,
    y: 6240,
    wires: [],
  },

  {
    id: 'support_analytics_in_001',
    type: 'http in',
    z: tabId,
    name: 'Support analytics daily',
    url: '/lk/support/analytics/daily',
    method: 'get',
    upload: false,
    swaggerDoc: '',
    x: 120,
    y: 6420,
    wires: [['support_analytics_fn_prepare_001']],
  },
  {
    id: 'support_analytics_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Support analytics daily prepare',
    func: fnSupportAnalyticsDailyPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 430,
    y: 6420,
    wires: [
      ['support_analytics_find_001'],
      ['support_analytics_http_resp_001'],
      ['support_analytics_debug_001'],
    ],
  },
  {
    id: 'support_analytics_find_001',
    type: 'mongodb4',
    z: tabId,
    clientNode: GAMES_MONGO4_CLIENT_ID,
    mode: 'collection',
    collection: 'support_messages',
    operation: 'find',
    output: 'toArray',
    maxTimeMS: '0',
    handleDocId: false,
    name: 'Find support analytics messages',
    x: 740,
    y: 6420,
    wires: [['support_analytics_fn_response_001']],
  },
  {
    id: 'support_analytics_fn_response_001',
    type: 'function',
    z: tabId,
    name: 'Support analytics daily response',
    func: fnSupportAnalyticsDailyResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1060,
    y: 6420,
    wires: [
      ['support_analytics_http_resp_001'],
      ['support_analytics_debug_001'],
    ],
  },
  {
    id: 'support_analytics_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 1360,
    y: 6420,
    wires: [],
  },
  {
    id: 'support_analytics_debug_001',
    type: 'debug',
    z: tabId,
    name: 'support analytics debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    statusVal: '',
    statusType: 'auto',
    x: 1360,
    y: 6460,
    wires: [],
  },
];

const combinedFlow = transformFlowToMongo4([...filteredFlow, ...supportNodes]);
fs.writeFileSync(outPath, `${JSON.stringify(combinedFlow, null, 2)}\n`, 'utf8');
fs.writeFileSync(importPath, `${JSON.stringify(supportNodes, null, 2)}\n`, 'utf8');

console.log(`Patched flow written to: ${outPath}`);
console.log(`Import flow written to: ${importPath}`);
console.log(`Total nodes: ${combinedFlow.length}`);
