import fs from 'node:fs';
import path from 'node:path';

const workspaceRoot = process.cwd();
const outPath = path.resolve(workspaceRoot, 'lk_max_webhook_nodes_import.json');
const fnDir = path.resolve(workspaceRoot, 'scripts/nodered_max_nodes');
const tabId = 'f9f8d8f2a833ab13';
const botConfigId = '55b05444842e7b84';

const readFn = (name) => fs.readFileSync(path.join(fnDir, name), 'utf8');
const fnMaxWebhookPrepare = readFn('fn_max_webhook_prepare.js');
const fnMaxClientLookupPrepare = readFn('fn_max_client_lookup_prepare.js');
const fnMaxSupportRoute = readFn('fn_max_support_route.js');
const fnMaxOutboxPullPrepare = readFn('fn_max_outbox_pull_prepare.js');
const fnMaxOutboxPullResponse = readFn('fn_max_outbox_pull_response.js');
const fnMaxOutboxDispatchPrepare = readFn('fn_max_outbox_dispatch_prepare.js');
const fnMaxOutboxAckPrepare = readFn('fn_max_outbox_ack_prepare.js');

const flow = [
  {
    id: tabId,
    type: 'tab',
    label: 'MAX support bridge',
    disabled: false,
    info: 'Единый MAX flow: прием MAX, авторизация по контакту, выбор станции, запись в ph-ab support API, отправка ответов администратора из outbox.',
  },
  {
    id: 'max_comment_001',
    type: 'comment',
    z: tabId,
    name: 'MAX support bridge',
    info: [
      'Настройте env в Node-RED:',
      '- SUPPORT_API_BASE_URL=http://<ph-ab-host>:3000/api',
      '- SUPPORT_INTEGRATION_TOKEN=<token>',
      '- MAX_BOT_WEBHOOK_SECRET=<secret, если используете webhook>',
      '',
      'Flow делает:',
      '1. Принимает входящие MAX через maxbot-receive или webhook.',
      '2. Проверяет клиента через ph-ab /support/clients/resolve.',
      '3. Записывает событие в ph-ab /support/dialogs/events.',
      '4. Отправляет сервисные ответы про номер телефона и выбор станции.',
      '5. Каждые 5 секунд тянет /support/outbox/pull?connector=MAX_BOT и отправляет ответы администратора в MAX.',
    ].join('\n'),
    x: 250,
    y: 120,
    wires: [],
  },
  {
    id: 'max_receive_001',
    type: 'maxbot-receive',
    z: tabId,
    name: 'MAX receive',
    bot: botConfigId,
    pollInterval: 3000,
    x: 120,
    y: 200,
    wires: [['max_webhook_fn_prepare_001']],
  },
  {
    id: 'max_webhook_in_001',
    type: 'http in',
    z: tabId,
    name: 'MAX webhook',
    url: '/integrations/max/webhook',
    method: 'post',
    upload: false,
    swaggerDoc: '',
    x: 120,
    y: 260,
    wires: [['max_webhook_fn_prepare_001']],
  },
  {
    id: 'max_webhook_fn_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Normalize MAX inbound',
    func: fnMaxWebhookPrepare,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 390,
    y: 220,
    wires: [
      ['max_client_lookup_prepare_001'],
      ['max_webhook_http_resp_001'],
      ['max_webhook_debug_001'],
    ],
  },
  {
    id: 'max_client_lookup_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Prepare support resolve',
    func: fnMaxClientLookupPrepare,
    outputs: 1,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 690,
    y: 200,
    wires: [['max_client_lookup_http_001']],
  },
  {
    id: 'max_client_lookup_http_001',
    type: 'http request',
    z: tabId,
    name: 'GET support client',
    method: 'use',
    ret: 'obj',
    paytoqs: 'ignore',
    url: '',
    tls: '',
    persist: false,
    proxy: '',
    insecureHTTPParser: false,
    authType: '',
    senderr: false,
    headers: [],
    x: 950,
    y: 200,
    wires: [['max_support_route_001']],
  },
  {
    id: 'max_support_route_001',
    type: 'function',
    z: tabId,
    name: 'Route MAX support flow',
    func: fnMaxSupportRoute,
    outputs: 3,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1220,
    y: 200,
    wires: [
      ['max_support_event_http_001'],
      ['max_send_001', 'max_outbound_debug_001'],
      ['max_webhook_debug_001'],
    ],
  },
  {
    id: 'max_support_event_http_001',
    type: 'http request',
    z: tabId,
    name: 'POST support event',
    method: 'use',
    ret: 'obj',
    paytoqs: 'ignore',
    url: '',
    tls: '',
    persist: false,
    proxy: '',
    insecureHTTPParser: false,
    authType: '',
    senderr: false,
    headers: [],
    x: 1490,
    y: 160,
    wires: [['max_support_event_debug_001']],
  },
  {
    id: 'max_send_001',
    type: 'maxbot-send',
    z: tabId,
    name: 'MAX send',
    bot: botConfigId,
    defaultChatId: '',
    x: 1760,
    y: 260,
    wires: [['max_send_debug_001', 'max_outbox_ack_prepare_001']],
  },
  {
    id: 'max_outbox_ack_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Prepare outbox ACK',
    func: fnMaxOutboxAckPrepare,
    outputs: 1,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 2020,
    y: 260,
    wires: [['max_outbox_ack_http_001']],
  },
  {
    id: 'max_outbox_ack_http_001',
    type: 'http request',
    z: tabId,
    name: 'POST outbox ACK',
    method: 'use',
    ret: 'obj',
    paytoqs: 'ignore',
    url: '',
    tls: '',
    persist: false,
    proxy: '',
    insecureHTTPParser: false,
    authType: '',
    senderr: false,
    headers: [],
    x: 2260,
    y: 260,
    wires: [['max_outbox_ack_debug_001']],
  },
  {
    id: 'max_outbox_poll_inject_001',
    type: 'inject',
    z: tabId,
    name: 'Poll MAX outbox',
    props: [
      { p: 'payload' },
      { p: 'topic', vt: 'str' },
    ],
    repeat: '5',
    crontab: '',
    once: true,
    onceDelay: 2,
    topic: '',
    payload: '',
    payloadType: 'date',
    x: 130,
    y: 420,
    wires: [['max_outbox_pull_prepare_001']],
  },
  {
    id: 'max_outbox_pull_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Prepare MAX outbox pull',
    func: fnMaxOutboxPullPrepare,
    outputs: 1,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 420,
    y: 420,
    wires: [['max_outbox_pull_http_001']],
  },
  {
    id: 'max_outbox_pull_http_001',
    type: 'http request',
    z: tabId,
    name: 'GET support outbox',
    method: 'use',
    ret: 'obj',
    paytoqs: 'ignore',
    url: '',
    tls: '',
    persist: false,
    proxy: '',
    insecureHTTPParser: false,
    authType: '',
    senderr: false,
    headers: [],
    x: 690,
    y: 420,
    wires: [['max_outbox_pull_response_001']],
  },
  {
    id: 'max_outbox_pull_response_001',
    type: 'function',
    z: tabId,
    name: 'Parse MAX outbox',
    func: fnMaxOutboxPullResponse,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 940,
    y: 420,
    wires: [
      ['max_outbox_split_001'],
      ['max_outbox_pull_debug_001'],
    ],
  },
  {
    id: 'max_outbox_split_001',
    type: 'split',
    z: tabId,
    name: 'Split MAX commands',
    splt: '\\n',
    spltType: 'str',
    arraySplt: 1,
    arraySpltType: 'len',
    stream: false,
    addname: '',
    x: 1180,
    y: 420,
    wires: [['max_outbox_dispatch_prepare_001']],
  },
  {
    id: 'max_outbox_dispatch_prepare_001',
    type: 'function',
    z: tabId,
    name: 'Prepare MAX dispatch',
    func: fnMaxOutboxDispatchPrepare,
    outputs: 2,
    timeout: '',
    noerr: 0,
    initialize: '',
    finalize: '',
    libs: [],
    x: 1450,
    y: 420,
    wires: [
      ['max_send_001'],
      ['max_outbox_error_debug_001'],
    ],
  },
  {
    id: 'max_webhook_http_resp_001',
    type: 'http response',
    z: tabId,
    name: '',
    x: 700,
    y: 280,
    wires: [],
  },
  {
    id: 'max_webhook_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX inbound debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 700,
    y: 320,
    wires: [],
  },
  {
    id: 'max_outbound_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX service reply debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 1500,
    y: 240,
    wires: [],
  },
  {
    id: 'max_support_event_debug_001',
    type: 'debug',
    z: tabId,
    name: 'Support ingest debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 1720,
    y: 160,
    wires: [],
  },
  {
    id: 'max_outbox_pull_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX outbox pull debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 1180,
    y: 500,
    wires: [],
  },
  {
    id: 'max_outbox_error_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX outbox error debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 1730,
    y: 480,
    wires: [],
  },
  {
    id: 'max_send_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX send debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 2000,
    y: 200,
    wires: [],
  },
  {
    id: 'max_outbox_ack_debug_001',
    type: 'debug',
    z: tabId,
    name: 'MAX outbox ack debug',
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: 'payload',
    targetType: 'msg',
    statusVal: '',
    statusType: 'auto',
    x: 2490,
    y: 260,
    wires: [],
  },
  {
    id: botConfigId,
    type: 'maxbot-config',
    name: 'MAX Bot',
  },
];

fs.writeFileSync(outPath, `${JSON.stringify(flow, null, 2)}\n`);
console.log(`Wrote ${outPath}`);
